<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0
                             http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>org.apache.hadoop.explorer</groupId>
    <artifactId>hadoop-explorer-parent</artifactId>
    <version>1.0.0</version>
    <packaging>pom</packaging>

    <name>Hadoop Explorer :: Platform</name>
    <description>Корневой Maven Reactor для платформы Hadoop Explorer</description>

    <modules>
        <module>backend/common-security-starter</module>
        <module>backend/replicator</module>
        <module>backend/yarn</module>
        <module>backend/hdfs</module>
        <module>backend/sql</module>
        <module>backend/spark</module>
    </modules>
</project>
