# Единый объединенный демо-стенд Hadoop Explorer (HDFS + SQL + YARN)
name: hadoop-explorer-demo-all

include:
  - path: ../infra/docker-compose.infra.yml
  - path: ../hdfs/docker-compose.yml
  - path: ../sql/docker-compose.yaml
  - path: ../yarn/docker-compose.yml
