connector.name=hive
hive.metastore.uri=thrift://hive-metastore-2:9083

# Metastore Kerberos Authentication
hive.metastore.authentication.type=KERBEROS
hive.metastore.service.principal=hive/hive-metastore-2.demo-platform-net@COMPANY.LOCAL
hive.metastore.client.principal=trino/trino-coordinator@COMPANY.LOCAL
hive.metastore.client.keytab=/etc/security/keytabs/trino.keytab

# HDFS Kerberos Authentication & Config Resources
fs.hadoop.enabled=true
hive.config.resources=/etc/hadoop/conf/core-site-cluster2.xml,/etc/hadoop/conf/hdfs-site-cluster2.xml
hive.hdfs.authentication.type=KERBEROS
hive.hdfs.trino.principal=trino/trino-coordinator@COMPANY.LOCAL
hive.hdfs.trino.keytab=/etc/security/keytabs/trino.keytab

