Client {
  com.sun.security.auth.module.Krb5LoginModule required
  useKeyTab=true
  keyTab="/etc/security/keytabs/hive.keytab"
  storeKey=true
  useTicketCache=false
  principal="hive/hive-server@COMPANY.LOCAL";
};
